---
title: "Yash Jain"
output: html_notebook
---
```{r}
library(ggplot2)
library(dplyr)
library(magrittr)
library(reshape2)

air_data <- read.csv("airline_delay.csv",na.strings="",stringsAsFactors=FALSE)

#Data Exploration
print("Summary of air_data")
summary(air_data)


#Removing rows with NA
air_data2 <- na.omit(air_data)
print("------------------------------------------------------")
print("Comparing dimensions before and afeter cleaning")
cat("\n")
cat("air_data:",dim(air_data))
cat("\n")
cat("air_data2:",dim(air_data2))
cat("\n")

print("------------------------------------------------------")
print("Summary of air_data2")
summary(air_data2) # to check if null
```


```{r}
#Question 1 

df_1 <- air_data2 %>%
  select(carrier_name, arr_delay) %>%
  group_by(carrier_name) %>%
  summarise(total_arrival_delay = sum(arr_delay)) %>%
  arrange(desc(total_arrival_delay))

head(df_1, 19)

ggplot(df_1, aes(y=total_arrival_delay, x=reorder(carrier_name, total_arrival_delay))) + 
  geom_bar(stat="identity")+
  labs(y="Total Arrival Delay", 
       x="Carrier Name", 
       fill = "Year",
       title="Question1: Airline vs Total Delays" ) + 
  coord_flip()
  
```

```{r}
#Question 2 

df_2 <- air_data2 %>%
  select(carrier_name, arr_delay,year) %>%
  group_by(carrier_name,year) %>%
  summarise(total_arrival_delay = sum(arr_delay)) %>%
  arrange(desc(total_arrival_delay))

dim(df_2)
head(df_2, 56)


ggplot(df_2, aes(y=total_arrival_delay,x=reorder(carrier_name,total_arrival_delay),
                                                 fill=factor(year))) + 
  geom_bar(stat="identity")+
  labs(y="Total Arrival Delay", 
       x="Carrier Name", 
       fill = "Year",
       title="Question2: Airline vs Total Delays by year") +
  coord_flip()
```

```{r}
#Question 3
df_3 <- air_data2 %>%
  filter((airport == "SFO") | (airport == "ORD") | (airport == "LGA") | 
           (airport == "LAX") | (airport == "JFK") | (airport == "EWR")|  
           (airport == "DFW") | (airport == "DEN") | (airport == "BOS")| 
           (airport == "ATL")) %>%
  select(airport, arr_delay,year) %>%
  group_by(airport,year) %>%
  summarise(total_arrival_delay = sum(arr_delay)) %>%
  arrange(desc(total_arrival_delay))

dim(df_3)
head(df_3, 56)


ggplot(df_3, aes(x=factor(year), y=factor(airport), fill=total_arrival_delay)) +
  geom_tile() +
  labs(x="Year", 
       y="Airport Name", 
       title="Question3: Heatmap of Airports and Total Arrival Delay",
       fill="Total Arrival Delay") 


```
```{r}
#Question 4
df_4 <- air_data2 %>%
  select(year, late_aircraft_delay, carrier_delay) %>%
  group_by(year) %>%
  summarise(carrier_delayy = sum(carrier_delay),
            late_aircraft_delayy = sum(late_aircraft_delay))
head(df_4)

test_4 <- melt(data=df_4, id="year")
head(test_4, 10)
colnames(test_4)

ggplot(test_4, aes(x=year, y= value, color=variable))+
  geom_line()+
  geom_point()+
  labs(x="Year",
       y="Mins",
       color="Delay_Type",
       title="Question4: Lineplot")
```

```{r}
#Question 5

df_5 <- air_data2 %>%
  filter(airport=="ATL" | airport=="BOS" | airport=="JFK")%>%
  select(airport, arr_delay) 

dim(df_5)

```

```{r}

ggplot(df_5, aes(x=airport, y=arr_delay))+
  geom_boxplot()+
  labs(x="Airport",
       y="Arrival delay in mins",
       title="Question 5A: Boxplot")
```

```{r}
ggplot(df_5, aes(x=airport, y=arr_delay))+
  geom_violin()+
  labs(x="Airport",
       y="Arrival delay in mins",
       title="Question 5B: Violin plot")
```

```{r}
ggplot(df_5, aes(x=arr_delay, fill=airport))+
  geom_area(stat='bin')+
  labs(x="Airport",
       y="Arrival delay in mins",
       title="Question 5C: Density plot")
```

```{r}
#Question 6:

#Import data
enplanement_df <- read.csv("enplanement_2017_csv.csv")
summary(enplanement_df)

#Preparing data

#Remove df records
enplanement_df2 <- na.omit(enplanement_df)

#Check dimensions of before and after removing NAs records
dim(enplanement_df)
dim(enplanement_df2)

#Change column name of dpwnloaded table
colnames(enplanement_df2)[which(names(enplanement_df2) == "Locid")] <- "airport"

#Change from factor to character
enplanement_df2$airport <- as.character(enplanement_df2$airport)


merged_df <- merge(air_data2, enplanement_df2, 
                   by.x="airport", by.y = "airport")

df_6 <- merged_df %>%
  select(airport, CY.17.Enplanements, arr_delay) %>%
  group_by(airport, CY.17.Enplanements) %>%
  summarise(sum(arr_delayy = arr_delay))

summary(df_6)
#Rename columns
colnames(df_6) <-c("airport", "Enplanement","Arrival_Delay")

#remove comma
df_6$Enplanement <- as.numeric(gsub(",","",df_6$Enplanement))

head(df_6,20)

```

```{r}
#Question 6 (continued)

#Scatter plot
ggplot(df_6, aes(x=Enplanement, y=Arrival_Delay))+
  geom_point()+
  labs(x="Enplanement",
       y="Arrival delay in mins",
       title="Question6 A: Scatter plot")





```

```{r}
#Scatter Plot on log scale
ggplot(df_6, aes(x=Enplanement, y=Arrival_Delay))+
  geom_point()+ 
  scale_x_continuous(trans='log10')+
  scale_y_continuous(trans='log10')+
  labs(x="Enplanement",
       y="Arrival delay in mins",
       title="Question6 B: Scatter plot with Log Scale ")





#Remove all free dataframes from working memory in the end
rm(enplanement_df, enplanement_df2, merged_df,air_data)
```

